env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  linebreak-style: 0
  react/react-in-jsx-scope: off
  no-underscore-dangle: ["error", { "allow": ["_embedded"] }]
  react/require-default-props: off
settings:
  react:
    version: detect
